default_stages:
  - commit
  - push

repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5  # or specific git tag
    hooks:
      - id: fasterer
      - id: forbid-binary
      - id: git-check  # Configure in .gitattributes
      - id: markdownlint # Configure in .mdlrc
      - id: script-must-have-extension
      - id: script-must-not-have-extension
      - id: shellcheck
        additional_dependencies: []
      - id: shfmt